alpha: 0.5
clip:
epochs: 130
lr: 0.01
lr_decay: step
lr_factor: 0.1
lr_schedule:
  - 100
  - 115
lr_throttle: False
optimizer: sgd
save_period: -1
test_batch_size: 300
test_mode: default
train_batch_size: 300
train_mode: progressive
val_period: 20
warmup_period: 10