alpha: 1
clip: 1
epochs: 150
lr: 0.001
lr_decay: step
lr_factor: 0.1
lr_schedule:
  - 60
  - 100
lr_throttle: False
optimizer: adam
save_period: -1
test_batch_size: 500
test_mode: default
train_batch_size: 100
train_mode: progressive
val_period: 20
warmup_period: 10